#! /usr/bin/env python

Import( 'env' )

env = env.Copy()

libofqf = env.SharedLibrary( target="ofqf", source= ['qoscclient.cpp','qosctypes.cpp','qoscserver.cpp'] )

env.InstallAs( env['PREFIX_LIB']+ '/libofqf.so.0.1', libofqf )
env.InstallAs( env['PREFIX_LIB']+ '/libofqf.so.0', libofqf )
env.InstallAs( env['PREFIX_LIB']+ '/libofqf.so', libofqf )

